spring.application.name=ms-identity
server.port=8086

spring.datasource.url=jdbc:oracle:thin:@localhost:1526/FREE
spring.datasource.username=SYSTEM
spring.datasource.password=Admin12345*
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

clients.ms-users.url=http://localhost:8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.flyway.enabled=false