services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-sgf
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 1234
      APP_USER: MS_USERS
      APP_USER_PASSWORD: 1234
    volumes:
      - oracle-data:/opt/oracle/oradata

  mysql-health:
    image: mysql:8.4
    container_name: mysql-health
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ms_health
      MYSQL_USER: MS_HEALTH
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-health-data:/var/lib/mysql

volumes:
  oracle-data:
  mysql-health-data: