ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER ms_auth IDENTIFIED BY Admin12345;
CREATE USER ms_border IDENTIFIED BY Admin12345;
CREATE USER ms_users IDENTIFIED BY Admin12345;
CREATE USER ms_identity IDENTIFIED BY Admin12345;
CREATE USER ms_visa IDENTIFIED BY Admin12345;
CREATE USER ms_logistics IDENTIFIED BY Admin12345;
CREATE USER ms_health IDENTIFIED BY Admin12345;
CREATE USER ms_audit IDENTIFIED BY Admin12345;
CREATE USER ms_alerts IDENTIFIED BY Admin12345;

GRANT DBA TO ms_auth;
GRANT DBA TO ms_border;
GRANT DBA TO ms_users;
GRANT DBA TO ms_identity;
GRANT DBA TO ms_visa;
GRANT DBA TO ms_logistics;
GRANT DBA TO ms_health;
GRANT DBA TO ms_audit;
GRANT DBA TO ms_alerts;