
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('superadmin', 'super123', 1);
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('security_admin', 'security123', 1);
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('audit_admin', 'audit123', 1);
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('alert_operator', 'alert123', 1);
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('border_agent_01', 'border123', 1);
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('border_supervisor', 'borderadmin123', 1);
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('visa_operator', 'visa123', 1);
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('identity_operator', 'identity123', 1);
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('health_operator', 'health123', 1);
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('logistics_operator', 'logistics123', 1);
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('infra_admin', 'infra123', 1);
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('migration_operator', 'migration123', 1);
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('citizen_demo', 'citizen123', 1);

INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'superadmin'), 'ROLE_SUPER_ADMIN');
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'security_admin'), 'ROLE_SECURITY_ADMIN');
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'audit_admin'), 'ROLE_AUDITOR');
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'alert_operator'), 'ROLE_ALERT_ANALYST');
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'border_agent_01'), 'ROLE_BORDER_AGENT');
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'border_supervisor'), 'ROLE_BORDER_SUPERVISOR');
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'visa_operator'), 'ROLE_VISA_OFFICER');
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'identity_operator'), 'ROLE_IDENTITY_OFFICER');
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'health_operator'), 'ROLE_HEALTH_OFFICER');
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'logistics_operator'), 'ROLE_LOGISTICS_OPERATOR');
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'infra_admin'), 'ROLE_INFRA_ADMIN');
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'migration_operator'), 'ROLE_MIGRATION_OPERATOR');
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'citizen_demo'), 'ROLE_CITIZEN');
