
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('superadmin', 'super123', 1);
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('security_admin', 'security123', 1);
INSERT INTO USUARIOS (USERNAME, PASSWORD, ACTIVO) VALUES ('audit_admin', 'audit123', 1);

INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'superadmin'), 'ROLE_SUPER_ADMIN');
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'security_admin'), 'ROLE_SECURITY_ADMIN');
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROL) VALUES ((SELECT ID FROM USUARIOS WHERE USERNAME = 'audit_admin'), 'ROLE_AUDITOR');


COMMIT;