spring.application.name=ms-health
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/ms_health?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=MS_HEALTH
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

clients.ms-users.url=http://localhost:8081
clients.ms-identity.url=http://localhost:8082

eureka.client.enabled=false
spring.flyway.enabled=false