spring.application.name=ms-alerts
server.port=8089

# ==========================================
# 1. BASE DE DATOS (Migrada a Oracle y Parametrizada)
# ==========================================
spring.datasource.url=jdbc:oracle:thin:@${DB_HOST:localhost}:${DB_PORT:1521}/FREE
spring.datasource.username=${DB_USER:ms_alerts}
spring.datasource.password=${DB_PASS:Admin12345}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# ==========================================
# 2. CONFIGURACIÓN DE KAFKA (Consumidor)
# ==========================================
spring.kafka.bootstrap-servers=${KAFKA_SERVER:localhost:9092}
spring.kafka.consumer.group-id=alerts-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# ==========================================
# 3. EUREKA
# ==========================================
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.port=8089

# ==========================================
# 4. MIGRACIONES
# ==========================================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs