CREATE TABLE USUARIOS (
                          ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                          USERNAME VARCHAR2(50) NOT NULL UNIQUE,
                          PASSWORD VARCHAR2(100) NOT NULL,
                          ACTIVO NUMBER(1,0) NOT NULL,

                          CONSTRAINT PK_USUARIOS PRIMARY KEY (ID)
);

CREATE TABLE USUARIO_ROLES (
                               USUARIO_ID NUMBER(19,0) NOT NULL,
                               ROL VARCHAR2(50) NOT NULL,

                               CONSTRAINT FK_USUARIO_ROLES_USUARIO
                                   FOREIGN KEY (USUARIO_ID)
                                       REFERENCES USUARIOS(ID)
);

COMMIT;