CREATE TABLE usuarios (
                          id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
                          username VARCHAR2(50) NOT NULL UNIQUE,
                          password VARCHAR2(100) NOT NULL,
                          activo NUMBER(1, 0) NOT NULL,
                          CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

CREATE TABLE usuario_roles (
                               usuario_id NUMBER(19, 0) NOT NULL,
                               rol VARCHAR2(50) NOT NULL,
                               CONSTRAINT fk_usuario_roles_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

COMMIT;