CREATE TABLE auditoria (
    id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    mensaje VARCHAR2(500) NOT NULL,
    emitido_por VARCHAR2(100),
    fecha_registro TIMESTAMP NOT NULL,
    CONSTRAINT pk_auditoria PRIMARY KEY (id)
);