spring.application.name=ms-bordercontrol
server.port=8085

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=MS_BORDERCONTROL
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

clients.ms-users.url=http://localhost:8081
clients.ms-identity.url=http://localhost:8082
clients.ms-visa.url=http://localhost:8083
clients.ms-health.url=http://localhost:8084

spring.kafka.bootstrap-servers=localhost:9092

eureka.client.enabled=false
spring.flyway.enabled=false